// lodge-web-types generates the browser's TypeScript declarations directly
// from the Go HTTP response contracts. It is a build tool, not a runtime
// dependency of either Lodge binary.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/toolazytoname/lodge/internal/domain"
	"github.com/toolazytoname/lodge/internal/hub"
	"github.com/toolazytoname/lodge/internal/shared"
)

const outputPath = "frontend/src/api.generated.d.ts"

func main() {
	check := flag.Bool("check", false, "fail when the committed declarations are stale")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected arguments")
	}
	content, err := generate()
	if err != nil {
		fatalf("generate: %v", err)
	}
	if *check {
		existing, err := os.ReadFile(outputPath)
		if err != nil || !bytes.Equal(existing, content) {
			fatalf("%s is stale; run npm run build:web", outputPath)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(outputPath, content, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func generate() ([]byte, error) {
	generator := typeGenerator{
		pending: []reflect.Type{
			reflect.TypeOf(hub.SessionResponse{}),
			reflect.TypeOf(hub.AgentSummary{}),
			reflect.TypeOf(hub.AgentServices{}),
			reflect.TypeOf(hub.AnnotationInput{}),
			reflect.TypeOf(hub.HostHistoryResponse{}),
			reflect.TypeOf(hub.EventsResponse{}),
			reflect.TypeOf(hub.WebLinkChecksResponse{}),
		},
		seen:  make(map[reflect.Type]bool),
		types: make(map[string]string),
	}
	for len(generator.pending) > 0 {
		current := generator.pending[0]
		generator.pending = generator.pending[1:]
		if err := generator.add(current); err != nil {
			return nil, err
		}
	}
	names := make([]string, 0, len(generator.types))
	for name := range generator.types {
		names = append(names, name)
	}
	sort.Strings(names)
	var output strings.Builder
	output.WriteString("// Code generated by cmd/lodge-web-types. DO NOT EDIT.\n\n")
	for _, name := range names {
		output.WriteString(generator.types[name])
		output.WriteByte('\n')
	}
	return []byte(strings.TrimRight(output.String(), "\n") + "\n"), nil
}

type typeGenerator struct {
	pending []reflect.Type
	seen    map[reflect.Type]bool
	types   map[string]string
}

func (generator *typeGenerator) add(value reflect.Type) error {
	value = indirect(value)
	if generator.seen[value] {
		return nil
	}
	generator.seen[value] = true
	if value.Kind() == reflect.String && value.Name() != "" {
		switch value {
		case reflect.TypeOf(shared.Exposure("")):
			generator.types[value.Name()] = "export type Exposure = \"local\" | \"tailnet\" | \"public\" | \"other\";\n"
		case reflect.TypeOf(shared.Kind("")):
			generator.types[value.Name()] = "export type Kind = \"docker\" | \"systemd\" | \"process\";\n"
		case reflect.TypeOf(domain.WebLinkState("")):
			generator.types[value.Name()] = "export type WebLinkState = \"reachable\" | \"degraded\" | \"unreachable\";\n"
		case reflect.TypeOf(domain.Severity("")):
			generator.types[value.Name()] = "export type Severity = \"info\" | \"warning\" | \"critical\";\n"
		case reflect.TypeOf(domain.EventState("")):
			generator.types[value.Name()] = "export type EventState = \"active\" | \"acknowledged\" | \"resolved\";\n"
		default:
			generator.types[value.Name()] = fmt.Sprintf("export type %s = string;\n", value.Name())
		}
		return nil
	}
	if value.Kind() != reflect.Struct || value.Name() == "" {
		return fmt.Errorf("unsupported root type %s", value)
	}
	var fields []string
	var bases []string
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		if !field.IsExported() {
			continue
		}
		tag := field.Tag.Get("json")
		parts := strings.Split(tag, ",")
		if parts[0] == "-" {
			continue
		}
		if field.Anonymous && parts[0] == "" {
			base := indirect(field.Type)
			if base.Name() == "" {
				return fmt.Errorf("anonymous field %s.%s has no named type", value.Name(), field.Name)
			}
			generator.enqueue(base)
			bases = append(bases, base.Name())
			continue
		}
		name := parts[0]
		if name == "" {
			name = field.Name
		}
		optional := false
		for _, option := range parts[1:] {
			optional = optional || option == "omitempty"
		}
		typeName, err := generator.typeScriptType(field.Type, optional)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", value.Name(), field.Name, err)
		}
		marker := ""
		if optional {
			marker = "?"
		}
		fields = append(fields, fmt.Sprintf("  %s%s: %s;", name, marker, typeName))
	}
	header := "export interface " + value.Name()
	if len(bases) > 0 {
		header += " extends " + strings.Join(bases, ", ")
	}
	generator.types[value.Name()] = header + " {\n" + strings.Join(fields, "\n") + "\n}\n"
	return nil
}

func (generator *typeGenerator) typeScriptType(value reflect.Type, optional bool) (string, error) {
	nullable := false
	if value.Kind() == reflect.Pointer {
		nullable = !optional
		value = value.Elem()
	}
	var result string
	switch value.Kind() {
	case reflect.Bool:
		result = "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		result = "number"
	case reflect.String:
		if value.Name() != "" && value.PkgPath() != "" {
			generator.enqueue(value)
			result = value.Name()
		} else {
			result = "string"
		}
	case reflect.Slice, reflect.Array:
		element, err := generator.typeScriptType(value.Elem(), false)
		if err != nil {
			return "", err
		}
		result = "Array<" + element + ">"
	case reflect.Struct:
		if value.Name() == "" {
			return "", fmt.Errorf("anonymous structs are not supported")
		}
		generator.enqueue(value)
		result = value.Name()
	default:
		return "", fmt.Errorf("unsupported Go type %s", value)
	}
	if nullable {
		result += " | null"
	}
	return result, nil
}

func (generator *typeGenerator) enqueue(value reflect.Type) {
	value = indirect(value)
	if !generator.seen[value] {
		generator.pending = append(generator.pending, value)
	}
}

func indirect(value reflect.Type) reflect.Type {
	for value.Kind() == reflect.Pointer {
		value = value.Elem()
	}
	return value
}

func fatalf(format string, values ...interface{}) {
	fmt.Fprintf(os.Stderr, "lodge-web-types: "+format+"\n", values...)
	os.Exit(1)
}
