// Code generated by cmd/lodge-web-types. DO NOT EDIT.

export interface AgentServices {
  agent: ServiceAgent;
  services: Array<ServiceView>;
}

export interface AgentSummary {
  id: string;
  name: string;
  online: boolean;
  lastSeen?: string;
  lastError?: string;
  cpus?: number;
  load1?: number;
  memUsedPct?: number;
  diskUsedPct?: number;
  serviceCount: number;
  publicCount: number;
}

export interface AnnotationInput {
  alias?: string;
  url?: string;
  hidden?: boolean;
  notes?: string;
}

export type Exposure = "local" | "tailnet" | "public" | "other";

export type Kind = "docker" | "systemd" | "process";

export interface Port {
  proto: string;
  port: number;
  bind: string;
  exposure: Exposure;
}

export interface ProxyRoute {
  scheme: string;
  host?: string;
  port: number;
  path: string;
  upstreams?: Array<string>;
}

export interface RouteView extends ProxyRoute {
  url?: string;
}

export interface Service {
  key: string;
  kind: Kind;
  name: string;
  status: string;
  since?: string;
  image?: string;
  unit?: string;
  composeProject?: string;
  composeService?: string;
  health?: string;
  pid?: number;
  ports?: Array<Port>;
  routes?: Array<ProxyRoute>;
  unidentified?: boolean;
  maxExposure: Exposure;
}

export interface ServiceAgent {
  id: string;
  name: string;
  online: boolean;
  lastSeen?: string;
  lastError?: string;
  agentVersion?: string;
}

export interface ServiceView extends Service {
  routes?: Array<RouteView>;
  alias?: string;
  url?: string;
  hidden: boolean;
  notes?: string;
}

export interface SessionResponse {
  authed: boolean;
  csrfToken?: string;
}
