// Code generated by cmd/lodge-web-types. DO NOT EDIT.

export interface ActionDefinition {
  id: string;
  targetKey: string;
  targetLabel: string;
  targetKind: ActionTargetKind;
  kind: ActionKind;
  description: string;
  confirmation: string;
  risk: ActionRisk;
}

export interface ActionExecutionInput {
  agentId: string;
  actionId: string;
  confirmation: string;
}

export interface ActionExecutionResponse {
  operation: OperationView;
  result?: ActionExecutionResult;
  errorKind?: string;
}

export interface ActionExecutionResult {
  ok: boolean;
  actionId: string;
  targetKey: string;
  kind: ActionKind;
  stateBefore?: string;
  stateAfter?: string;
  summary?: string;
  logs?: Array<string>;
  errorKind?: string;
}

export type ActionKind = "start" | "stop" | "restart" | "logs";

export type ActionRisk = "read" | "change" | "disruptive";

export type ActionTargetKind = "systemd" | "docker";

export interface AgentActionsResponse {
  agentId: string;
  agentName: string;
  agentVersion?: string;
  actions: Array<ActionDefinition>;
}

export interface AgentDeploymentsResponse {
  agentId: string;
  agentName: string;
  agentVersion?: string;
  deployments: Array<DeploymentDefinition>;
}

export interface AgentServices {
  agent: ServiceAgent;
  services: Array<ServiceView>;
}

export interface AgentSummary {
  id: string;
  name: string;
  online: boolean;
  lastSeen?: string;
  lastError?: string;
  cpus?: number;
  load1?: number;
  memUsedPct?: number;
  diskUsedPct?: number;
  serviceCount: number;
  publicCount: number;
  security?: SecurityPosture;
}

export interface AnnotationInput {
  alias?: string;
  url?: string;
  hidden?: boolean;
  notes?: string;
}

export interface DeploymentDefinition {
  id: string;
  stackKey: string;
  stackLabel: string;
  kind: DeploymentKind;
  releaseId: string;
  releaseLabel: string;
  image: string;
  currentReleaseId?: string;
  previousReleaseId?: string;
  description: string;
  confirmation: string;
  risk: ActionRisk;
}

export interface DeploymentExecutionInput {
  agentId: string;
  deploymentId: string;
  confirmation: string;
}

export interface DeploymentExecutionResponse {
  operation: OperationView;
}

export type DeploymentKind = "deploy" | "rollback";

export type EventState = "active" | "acknowledged" | "resolved";

export interface EventView {
  id: string;
  agentId: string;
  kind: string;
  severity: Severity;
  state: EventState;
  title: string;
  detail?: string;
  firstObservedAt: string;
  lastObservedAt: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
}

export interface EventsResponse {
  agentId?: string;
  events: Array<EventView>;
}

export type Exposure = "local" | "tailnet" | "public" | "other";

export interface HostHistoryResponse {
  agentId: string;
  points: Array<ObservationHistoryPoint>;
}

export type Kind = "docker" | "systemd" | "process";

export interface ObservationHistoryPoint {
  observedAt: string;
  online: boolean;
  lastError?: string;
  agentVersion?: string;
  cpus?: number;
  load1?: number;
  memoryUsedPct?: number;
  diskUsedPct?: number;
  workloadCount: number;
  failedWorkloadCount: number;
  wildcardEndpointCount: number;
  warningCount: number;
}

export type OperationKind = "start" | "stop" | "restart" | "logs" | "deploy" | "rollback";

export type OperationState = "requested" | "running" | "succeeded" | "failed" | "rolled_back";

export interface OperationView {
  id: string;
  agentId: string;
  targetKey?: string;
  kind: OperationKind;
  state: OperationState;
  requestedBy: string;
  requestedAt: string;
  startedAt?: string;
  finishedAt?: string;
  resultSummary?: string;
  errorKind?: string;
}

export interface OperationsResponse {
  agentId?: string;
  operations: Array<OperationView>;
}

export interface Port {
  proto: string;
  port: number;
  bind: string;
  exposure: Exposure;
}

export interface ProxyRoute {
  scheme: string;
  host?: string;
  port: number;
  path: string;
  upstreams?: Array<string>;
}

export interface RouteView extends ProxyRoute {
  url?: string;
}

export interface SecurityPosture {
  sshListener: SecuritySetting;
  sshPasswordAuthentication: SecuritySetting;
  sshRootLogin: SecuritySetting;
  sshPublicKeyAuthentication: SecuritySetting;
  firewall: SecuritySetting;
  fail2ban: SecuritySetting;
  tailscale: SecuritySetting;
}

export type SecuritySetting = string;

export interface Service {
  key: string;
  kind: Kind;
  name: string;
  status: string;
  since?: string;
  image?: string;
  unit?: string;
  composeProject?: string;
  composeService?: string;
  health?: string;
  pid?: number;
  ports?: Array<Port>;
  routes?: Array<ProxyRoute>;
  unidentified?: boolean;
  maxExposure: Exposure;
}

export interface ServiceAgent {
  id: string;
  name: string;
  online: boolean;
  lastSeen?: string;
  lastError?: string;
  agentVersion?: string;
}

export interface ServiceView extends Service {
  routes?: Array<RouteView>;
  alias?: string;
  url?: string;
  hidden: boolean;
  notes?: string;
}

export interface SessionResponse {
  authed: boolean;
  csrfToken?: string;
}

export type Severity = "info" | "warning" | "critical";

export interface WebLinkCheckSummary {
  total: number;
  reachable: number;
  degraded: number;
  unreachable: number;
  checkedAt?: string;
}

export interface WebLinkCheckView {
  agentId: string;
  serviceKey: string;
  url: string;
  state: WebLinkState;
  httpStatus?: number;
  latencyMs: number;
  errorKind?: string;
  checkedAt: string;
}

export interface WebLinkChecksResponse {
  checks: Array<WebLinkCheckView>;
  summary: WebLinkCheckSummary;
}

export type WebLinkState = "reachable" | "degraded" | "unreachable";
